FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies needed for Prisma + Alpine
RUN apk add --no-cache bash curl libc6-compat

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
ARG DATABASE_URL=fake
RUN npx prisma generate

COPY . .

ENV SKIP_DB_INIT=true

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm start"]
