FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
ARG DATABASE_URL=fake
ENV DATABASE_URL=$DATABASE_URL
RUN npx prisma generate

COPY . .

ENV SKIP_DB_INIT=true

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# In produzione, SKIP_DB_INIT non serve più
ENV SKIP_DB_INIT=false
EXPOSE 3000
CMD ["npm", "start"]
